version: 1
formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s'
  minimal:
    format: '%(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: INFO
    formatter: detailed
    filename: logs/data_ingestion.log
    encoding: utf8

  error_file:
    class: logging.FileHandler
    level: ERROR
    formatter: detailed
    filename: logs/errors.log
    encoding: utf8

  metrics_file:
    class: logging.FileHandler
    level: INFO
    formatter: minimal
    filename: logs/metrics.log
    encoding: utf8

loggers:
  src:
    level: INFO
    handlers: [console, file]
    propagate: no

  src.pipeline:
    level: INFO
    handlers: [console, file, metrics_file]
    propagate: no

  src.connectors:
    level: INFO
    handlers: [console, file]
    propagate: no

  src.classifiers:
    level: INFO
    handlers: [console, file, metrics_file]
    propagate: no

  src.utils:
    level: INFO
    handlers: [console, file]
    propagate: no

  web_dashboard:
    level: INFO
    handlers: [console, file]
    propagate: no

root:
  level: INFO
  handlers: [console, file, error_file]
  propagate: no